### ISSUE TITLE
Rendering Problems when Previewing the Layout in Intellij IDEA

### ISSUE THREAD

**Issue by realaboo** [dmytrodanylyk/shadow-layout#12]
The library works like a charm when running on devices. Could you please add supports to preview it in Intellij IDEA (and Android Studio)? Or at least eliminate these errors: 

Rendering Problems The following classes could not be instantiated:

- com.dd.ShadowLayout (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.AssertionError   at android.content.res.BridgeResources.getDimension(BridgeResources.java:345)   at com.dd.ShadowLayout.initAttributes(ShadowLayout.java:71)   at com.dd.ShadowLayout.initView(ShadowLayout.java:45)   at com.dd.ShadowLayout.<init>(ShadowLayout.java:28)   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)   at android.view.LayoutInflater.inflate(LayoutInflater.java:479)   at android.view.LayoutInflater.inflate(LayoutInflater.java:385) Copy stack to clipboard

Thanks a lot for the great work!

**Comment by dmytrodanylyk** [comment]
@realaboo ok, woll update soon
